### PR TITLE
fixes #778

### LINKED ISSUE #778: add EFA devices to AWS named_resources
## Description
For EFA devices to be available within Batch job container they have to be mapped via Job Definition (created by torchx's `aws_batch_scheduler`).
It has been made possible to register EFA devices when [this code](https://github.com/pytorch/torchx/blob/61533150ccd277ef002398559de54e5f578dd666/torchx/schedulers/devices.py#L26) was introduced.

All that's left is to add these devices to AWS named_resources that supports them.

## Motivation/Background
EFA significantly increases the throughput for cross-device communication. It is opt-in for the training job to use if or not (using an `env` flag), but it won't work unless it's registered in the Batch Job Definition.

## Detailed Proposal
Simple add EFA devices for AWS named_resources that have them.

## Alternatives
- Otherwise the customers have to copy-paste and register modified named_resources

## Additional context/links
* https://github.com/pytorch/torchx/blob/61533150ccd277ef002398559de54e5f578dd666/torchx/schedulers/devices.py#L26
* https://docs.aws.amazon.com/batch/latest/userguide/efa.html

### PR DESCRIPTION
**Pull request by clumsy**
adding EFA devices to AWS named_resources

Test plan:
* added new assertions to existing AWS named_resources tests

### CODE REVIEW

**Comment by clumsy** [comment]
For your consideration, @kiukchung

**Comment by kiukchung** [comment]
lgtm thanks for the PR! Waiting for CI to pass before merging

**Review by kiukchung — APPROVED** [review]

**Comment by clumsy** [comment]
Fixed the formatting to address linter error, @kiukchung.

**Comment by clumsy** [comment]
Let me know if any changes are needed, @kiukchung. The tests seem to pass.

**Pull request merged**
