### PR TITLE
Support Ray 2.0 by getting rid of ray.train.util dependency

### PR DESCRIPTION
**Pull request by ntlm1686**
Ray 2.0 made get_address_and_port no longer public + added a bunch of pyre changes. We need to find a replacement for get_address_and_port, fix the types and then upgrade to Ray 2.0.

#584 

Test plan:

CI

### CODE REVIEW

**Comment by ljjsalt** [comment]
OK, duplicated #586

**Review by d4l3k — APPROVED** [review]
@ljjsalt can you update the pyre and fix the unit tests?

`pyre --output=json | pyre-upgrade fixme`

**Comment by d4l3k** [comment]
you'll have to unpin ray version as well https://github.com/pytorch/torchx/commit/b70811e11ed4ed5d3b9dca62f177177135b7990f

**Comment by ljjsalt** [comment]
@d4l3k I can. 
But I think there is something else needs to be fixed as well.
For example, `ray.node.Node` is moved to `ray._private.node.Node`.

Should we find a replacement or just use `ray._private`?

**Comment by d4l3k** [comment]
@ljjsalt you can just change that type to "object" since we don't actually interact with it (just pass it back to Ray) and it seems like those ray methods are untyped

**Comment by ljjsalt** [comment]
> @ljjsalt can you update the pyre and fix the unit tests?
> 
> `pyre --output=json | pyre-upgrade fixme`

@d4l3k It seems this command generated many pyre errors.

**Comment by d4l3k** [comment]
ah yeah -- that probably wasn't quite the right thing to do -- looks like you were missing some local dependencies. Did you install all of dev-requirements.txt? Are you running in a virtualenv?

**Comment by ljjsalt** [comment]
> ah yeah -- that probably wasn't quite the right thing to do -- looks like you were missing some local dependencies. Did you install all of dev-requirements.txt? Are you running in a virtualenv?

@d4l3k Yeah, it's a environment just for torchx. So I tried to install dependencies from `requirements.txt` and `dev-requirements.txt` on both my Macbook and Linux server.

Then I install `pyre` with `pyre-check`, I got the same error on both machines,

```
(torchx-dev) > $ ./pyre.sh                                  [±port_addr_ray2 ✓]
+ pyre --version
Traceback (most recent call last):
  File "/home/jiajie/miniconda3/envs/torchx-dev/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/home/jiajie/miniconda3/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/pyre.py", line 19, in <module>
    from . import (
  File "/home/jiajie/miniconda3/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/__init__.py", line 6, in <module>
    from . import (  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401  # noqa F401
  File "/home/jiajie/miniconda3/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/persistent.py", line 43, in <module>
    from . import (
  File "/home/jiajie/miniconda3/envs/torchx-dev/lib/python3.8/site-packages/pyre_check/client/commands/language_server_protocol.py", line 15, in <module>
    from pyre_extensions import override
ImportError: cannot import name 'override' from 'pyre_extensions' (/home/jiajie/miniconda3/envs/torchx-dev/lib/python3.8/site-packages/pyre_extensions/__init__.py)
```

Is there a specific pyre version for me to use?

**Comment by ljjsalt** [comment]
@d4l3k Dependencies are installed with `pip install -e '.[dev]'`. Except from `pyre-extensions==0.0.21`, only `0.0.29` works for me. Then I keep getting different pyre outputs from CI.

**Comment by ljjsalt** [comment]
I didn't even see the code which causes the pyre error
image
image

**Comment by d4l3k** [comment]
Closing since we support ray 2.x now

**Pull request closed without merging**
