### PR TITLE
Update black version and usort version to match what linter is using in phabricator

### PR DESCRIPTION
**Pull request by yikaiMeta**
Test plan:

### CODE REVIEW

**Comment by yikaiMeta** [comment]
This is how I get the version number of internal linter:
Screenshot 2024-02-27 at 12 33 29 PM

**Comment by manav-a** [comment]
Did you run the formatter on the repo after the version change?

**Comment by yikaiMeta** [comment]
Running the formatter shows that there are no changes due to version change.
`black --version`
`black ~/torchx/torchx/`
All done! ✨ 🍰 ✨
212 files left unchanged.

**Comment by yikaiMeta** [comment]
running 
`pyfmt --usort ~/torchx/torchx/`
shows no files are changed.

**Pull request merged**
